#!/bin/bash 

# Paths
globalWorkingPath="$(cd "$(dirname "$0")" && pwd)"
globalAssetsDirectory="assets"
globalConfDirectory="configurations"
globalPkgDirectory="packages"
globalPrfDirectory="profiles"
globalBinPath="$globalWorkingPath/bin"
globalTemporaryPath="$globalWorkingPath/tmp"
globalAssetsPath="$globalWorkingPath/$globalAssetsDirectory"
globalConfigPath="$globalWorkingPath/$globalConfDirectory"
globalInstallPath="$globalWorkingPath/$globalPkgDirectory"
globalProfilesPath="$globalWorkingPath/$globalPrfDirectory"

# Parameters
source "$globalBinPath/parameters"
for param in "$@"; do
	case "$param" in
		--*)
			parameters "$param" ;;
		-[!-]*)
			for (( i=1; i<${#param}; i++ )); do
				parameters "${param:$i:1}"
			done ;;
	esac
done

# Global environnement variables
globalDebug=${paramDebug:-false}
globalVerbose=${paramVerbose:-false}
globalConfigure=${paramConfigure:-false}
globalForce=${paramForce:-false}
globalClean=${paramClean:-true}
globalHelp=${paramHelp:-false}
globalSetup=${paramSetup:-false}
globalPattern=${paramPattern}
globalColor=${paramColor:-false}
globalProfil=${paramProfil:-false}
globalList=${paramList:-false}
globalProfilName=${paramProfilName}
globalOverrideAssetsPath="${paramOverridePath:-$globalWorkingPath}/${globalAssetsDirectory}${paramOverride-/user}"
globalOverrideConfigPath="${paramOverridePath:-$globalWorkingPath}/${globalConfDirectory}${paramOverride-/user}"
globalOverrideInstallPath="${paramOverridePath:-$globalWorkingPath}/${globalPkgDirectory}${paramOverride-/user}"
globalOverrideProfilesPath="${paramOverridePath:-$globalWorkingPath}/${globalPrfDirectory}${paramOverride-/user}"

# Include bin
for binFile in $globalBinPath/*; do
   source "$binFile"
done

# Help
if $globalHelp; then
	logInfo --text="${globalGras}${globalSouligne}Liste des options${globalResetColor}${globalGras}"
	echo -e "c|--color)\nC|--configure)\nd|--debug)\nh|--help)\ni|--force-install)\nl|--list)\nn|--no-clean)\ns|--setup)\nv|--verbose\n--pattern=)\n--profil=)\n--overridePath=)"
	exit 0
fi

# List Profiles
if $globalList; then
	(
		logInfo --text="${globalGras}${globalSouligne}LISTE DE TOUS LES PACKAGES${globalResetColor}${globalGras}"
		for installFile in $globalInstallPath/*; do
			installFileWithoutPrefixe=${installFile##*/}
			logInfo --text="  - ${installFileWithoutPrefixe%.*}" --color="$globalJaune"
		done		
		logInfo --text="\n${globalGras}${globalSouligne}LISTE DE TOUS LES PROFILS${globalResetColor}${globalGras}"
		for profileFile in $globalProfilesPath/*; do
			if [ ! -d $profileFile ]; then
				profileFileWithoutPath=${profileFile##*/}
				logInfo --text="  ${profileFileWithoutPath%.*}" --color="$globalItalique$globalBleu"
				for line in $(cat --squeeze-blank "$profileFile"); do
					logInfo --text="    - ${line#*-}" --color="$globalCyan"
				done
			fi
		done
	) | less -R
	exit 0
fi

# Setup
if $globalSetup; then
	setupProject
	exit 0
fi

# Errors
if [ -z $paramPattern ] && ! $globalProfil; then
	logError --text="Paramètre --profil ou --pattern requis"
	exit 1
fi
if [ -z $paramOverride ] && [ ! -d $paramOverridePath ]; then
	logError --text="Répertoire de surcharge introuvable (--overridePath error)"
	exit 1
fi

# Temporary directory
if [ ! -d "$globalTemporaryPath" ]; then
	mkdir --parents "$globalTemporaryPath"
fi

# Provision
if $globalProfil; then
	installProfile --profile="$globalProfilName"
else 
	installPkg --pattern="$globalPattern"
fi

# Clean System
if $globalClean; then
	cleanAll
fi

exit 0