#!/bin/bash 

# Paths
globalWorkingPath="$(cd "$(dirname "$0")" && pwd)"
globalBinPath=$globalWorkingPath/bin
globalInstallPath=$globalWorkingPath/packages
globalConfigPath=$globalWorkingPath/configurations
globalConfigUserPath=$globalConfigPath/user
globalAssetsPath=$globalWorkingPath/assets
globalTemporaryPath=$globalWorkingPath/tmp
globalProfilsPath=$globalWorkingPath/profiles

# Include bin
for binFile in $globalBinPath/*; do
   source "$binFile"
done

# Parameters
for param in "$@"; do
	case "$param" in
		--*)
			parameters "$param" ;;
		-[!-]*)
			for (( i=1; i<${#param}; i++ )); do
				parameters "${param:$i:1}"
			done ;;
	esac
done

# Global environnement variables
globalDebug=${paramDebug:-false}
globalVerbose=${paramVerbose:-false}
globalConfigure=${paramConfigure:-false}
globalForce=${paramForce:-false}
globalClean=${paramClean:-true}
globalHelp=${paramHelp:-false}
globalSetup=${paramSetup:-false}
globalPattern=${paramPattern}
globalColor=${paramColor:-false}
globalProfil=${paramProfil:-false}
globalList=${paramList:-false}
globalProfilName=${paramProfilName}

# Help
if $globalHelp; then
	logInfo --text="${globalGras}${globalSouligne}Liste des options${globalResetColor}${globalGras}"
	echo -e "c|--color)\nC|--configure)\nd|--debug)\nh|--help)\ni|--force-install)\nl|--list)\nn|--no-clean)\ns|--setup)\nv|--verbose\n--pattern=)\n--profil=)"
	exit 0
fi

# Profiles
if $globalList; then
	(
		logInfo --text="${globalGras}${globalSouligne}LISTE DE TOUS LES PACKAGES${globalResetColor}${globalGras}"
		for installFile in $globalInstallPath/*; do
			installFileWithoutPrefixe=${installFile##*/}
			logInfo --text="  - ${installFileWithoutPrefixe%.*}" --color="$globalJaune"
		done		
		logInfo --text="\n${globalGras}${globalSouligne}LISTE DE TOUS LES PROFILS${globalResetColor}${globalGras}"
		for profilFile in $globalProfilsPath/*; do
			profileFileWithoutPath=${profilFile##*/}
			logInfo --text="  ${profileFileWithoutPath%.*}" --color="$globalItalique$globalBleu"
			for line in $(cat --squeeze-blank "$profilFile"); do
				logInfo --text="    - ${line#*-}" --color="$globalCyan"
			done
		done
	) | less -R
	exit 0
fi

# Setup
if $globalSetup; then
	setupProject
	exit 0
fi

# Errors
if [ -z $paramPattern ] && ! $globalProfil; then
	logError --text="Paramètre --profil ou --pattern requis"
	exit 1
fi

# Temporary directory
if [ ! -d "$globalTemporaryPath" ]; then
	mkdir --parents "$globalTemporaryPath"
fi

# Provision
if $globalProfil; then
	installProfile --profil="$globalProfilName"
else 
	installPkg --pattern="$globalPattern"
fi

# Clean System
if $globalClean; then
	cleanAll
fi

exit 0